version: '3.8'

services:
  postgres:
    container_name: gestao_vagas_postgres
    image: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=iago_admin
      - POSTGRES_PASSWORD=0123456
      - POSTGRES_DB=gestao_vagas
